name: Build and Publish

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest
        if: "!contains(github.event.head_commit.message, 'ci skip')"
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2-beta
              with:
                node-version: '12'
            - name: Install dependencies
              run: yarn install --frozen-lockfile
            - name: Build library
              run: yarn build
            - name: Show files to publish
              run: npm publish --dry-run
            - name: Upload build result
              uses: actions/upload-artifact@v2
              with:
                name: thu-learn-lib
                path: lib/

    publish:
        needs: build
        runs-on: ubuntu-latest
        if: "startsWith(github.ref, 'refs/tags/v')"
        steps:
            - uses: actions/checkout@v2

            - name: Download build result
              uses: actions/download-artifact@v2
              with:
                name: thu-learn-lib
                path: lib/

            - uses: actions/setup-node@v1
              with:
                node-version: '10.x'
                registry-url: 'https://registry.npmjs.org'

            - name: Publish to NPM
              run: npm publish
              env:
                NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}                 


            - uses: actions/setup-node@v1
              with:
                registry-url: 'https://npm.pkg.github.com'

            - name: Publish to GitHub Package Registry
              run: npm publish
              env:
                NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
